import React, { useEffect, useState } from 'react'
import Image from 'next/image';
import styles from '@/styles/ProfileDashboard.module.css'
import Head from 'next/head'
import { IoMdSettings } from 'react-icons/io';
import { BsBoxArrowLeft } from 'react-icons/bs';
import { BsFillPencilFill } from 'react-icons/bs';
import PostCard from '../components/PostCard/postCard'
import EditProfile from '../components/EditProfile/EditProfile'
import { useRouter } from 'next/router';
import user from '../assets/user.jpg'
import { useSelector, useDispatch } from 'react-redux';
import { setShowEditPopup, logout } from '@/store/slices';

const Profile = () => {

  const [activeComponent, setActiveComponent] = useState('posts');
  const [showSettings, setShowSettings] = useState(false)

  const showEditPopup = useSelector((state) => state.editPopup.value)
  const currentUser = useSelector((state) => state.currentUser.userData)

  const router = useRouter();
  const dispatch = useDispatch();

  const handleComponentChange = (componentName) => {
    setActiveComponent(componentName);
  };

  useEffect(() => {
    console.log(currentUser)
  }, [activeComponent])
  return (
    <>
      <Head>
        <title>KachraDekho | Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* edit profile */}
      {showEditPopup === 'true' && <div className={styles.edit_popup}>
        <EditProfile />
      </div>}

      {/* profile details */}
      <div className={styles.container}>

        <button
          className={styles.back_button}
          onClick={() => router.push('/')}
        ><BsBoxArrowLeft /> Back</button>

        <div className={styles.inner_container}>

          {/* upper part for basic details */}
          <div className={styles.details_hld}>
            <div className={styles.photo}>
              <Image
                alt='user_photo'
                src={user}
                layout='responsive'
                objectFit='cover'
                width={'100%'}
                height={'100%'}

              />
            </div>
            <div className={styles.change_image}>
              <BsFillPencilFill />
              {/* <div className={styles.change_popup}><p>Change Photo jjjg</p></div> */}
            </div>
            <div className={styles.name_post_hld}>
              <div className={styles.name_bio_hld}>
                <div className={styles.name}>
                  <span>{currentUser.name}</span>
                  <button onClick={() => dispatch(setShowEditPopup())}>Edit Profile</button>
                  <IoMdSettings size={30}
                    onClick={() => setShowSettings(!showSettings)}
                    style={{ cursor: "pointer" }}
                  />

                  {/* settings */}
                  {showSettings && <div className={styles.settings}>
                    <ul>
                      <li
                        onClick={() => router.push("/ChangePassword")}
                      >Change Password</li>
                      <li
                        onClick={() => {
                          dispatch(logout())
                          router.push('/')
                          // window.location.reload()
                        }}>Logout</li>
                    </ul>
                  </div>}
                </div>
                <span>{currentUser.bio}</span>
                {/* <span>date of birth</span> */}
                <span>{currentUser.gender}</span>
                <span>{currentUser.contactNo}</span>
                <span>{currentUser.address}, {currentUser.city}, {currentUser.state}, {currentUser.country}</span>
              </div>
              <div className={styles.post}>
                <span>100 posts</span>
                <span>100 saved</span>
              </div>
            </div>
          </div>

          {/* bottom part for posts */}
          <div className={styles.post_details}>
            <div className={styles.details_type}>
              <span
                className={`${activeComponent === 'posts' ? styles.activePost : ''
                  }`}
                onClick={() => handleComponentChange('posts')}>Posts</span>
              <span
                className={`${activeComponent === 'saved' ? styles.activePost : ''
                  }`}
                onClick={() => handleComponentChange('saved')}>Saved</span>
            </div>

            {/* show posts */}
            <div className={styles.slider}>
              {activeComponent === "posts" && <div
                className={`${styles.sliderWrapper} ${activeComponent === 'posts' ? styles.active : ''
                  }`}
              >
                <PostCard />
                <PostCard />
              </div>}
              {activeComponent === "saved" && <div
                className={`${styles.sliderWrapper} ${activeComponent === 'saved' ? styles.active : ''
                  }`}
              >
                <PostCard />
                <PostCard />
              </div>}
            </div>
          </div>
        </div>

      </div>
    </>
  )
}

export default Profile
