import React, { useEffect, useState } from 'react'
import styles from '@/styles/ProfileDashboard.module.css'
import Head from 'next/head'
import { IoMdSettings } from 'react-icons/io';
import PostCard from '../components/PostCard/postCard'
import EditProfile from '../components/EditProfile/EditProfile'
import { useRouter } from 'next/router';

const Profile = () => {

  const [activeComponent, setActiveComponent] = useState('posts');
  const [showEditPopup, setShowEditPopup] = useState(false)
  const [showSettings, setShowSettings] = useState(false)

  const router = useRouter();

  const handleComponentChange = (componentName) => {
    setActiveComponent(componentName);
  };

  useEffect(() => {

  }, [activeComponent])
  return (
    <>
      <Head>
        <title>KachraDekho | Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* edit profile */}
      {showEditPopup && <div className={styles.edit_popup}>
        <EditProfile
          showEditPopup={showEditPopup}
          setShowEditPopup={setShowEditPopup} />
      </div>}

      {/* profile details */}
      <div className={styles.container}>

        <div className={styles.inner_container}>

          {/* upper part for basic details */}
          <div className={styles.details_hld}>
            <div className={styles.photo}>
              <img src="https://images.unsplash.com/photo-1502685104226-ee32379fe3f6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx" />
            </div>
            <div className={styles.name_post_hld}>
              <div className={styles.name_bio_hld}>
                <div className={styles.name}>
                  <span>Umesh Kumar Bhatiya</span>
                  <button onClick={() => setShowEditPopup(!showEditPopup)}>Edit Profile</button>
                  <IoMdSettings size={30}
                    onClick={() => setShowSettings(!showSettings)}
                    style={{ cursor: "pointer" }}
                  />

                  {/* settings */}
                  {showSettings && <div className={styles.settings}>
                    <ul>
                      <li
                      onClick={()=> router.push("/ChangePassword")}
                      >Change Password</li>
                      <li>Logout</li>
                    </ul>
                  </div>}
                </div>
                <span>bio</span>
                <span>date of birth</span>
                <span>gender</span>
                <span>contact</span>
                <span>address</span>
              </div>
              <div className={styles.post}>
                <span>100 posts</span>
                <span>100 saved</span>
              </div>
            </div>
          </div>

          {/* bottom part for posts */}
          <div className={styles.post_details}>
            <div className={styles.details_type}>
              <span
                className={`${activeComponent === 'posts' ? styles.activePost : ''
                  }`}
                onClick={() => handleComponentChange('posts')}>Posts</span>
              <span
                className={`${activeComponent === 'saved' ? styles.activePost : ''
                  }`}
                onClick={() => handleComponentChange('saved')}>Saved</span>
            </div>

            {/* show posts */}
            <div className={styles.slider}>
              {activeComponent === "posts" && <div
                className={`${styles.sliderWrapper} ${activeComponent === 'posts' ? styles.active : ''
                  }`}
              >
                <PostCard />
                <PostCard />
              </div>}
              {activeComponent === "saved" && <div
                className={`${styles.sliderWrapper} ${activeComponent === 'saved' ? styles.active : ''
                  }`}
              >
                <PostCard />
                <PostCard />
              </div>}
            </div>
          </div>
        </div>

      </div>
    </>
  )
}

export default Profile
